# Generated by Django 5.2.17 on 2026-08-20 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter your number in international format, digits only, e.g. 447700900000.', regex='^[1-9]\\d{6,14}$')])),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set the first time a code sent to this number is accepted.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
