# Generated by Django 5.2.17 on 2026-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='face_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What the ticket cost. Shown on the transfer screen so the person giving it away can see what they are giving away.', max_digits=8),
        ),
    ]
